# Generated by Django 5.0.4 on 2024-05-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tags", models.CharField(max_length=500)),
                ("is_watched", models.BooleanField(default=False)),
                ("ott", models.CharField(default="unknown", max_length=100)),
            ],
        ),
    ]
