# Generated by Django 5.0.4 on 2024-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0002_streamplatform_watchlist_delete_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamplatform",
            name="about",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="streamplatform",
            name="website",
            field=models.URLField(max_length=100),
        ),
    ]
