# Generated by Django 5.0.4 on 2024-05-06 08:35
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0003_alter_streamplatform_about_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlist",
                to="watchlist.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
