# Generated by Django 5.0.4 on 2024-05-08 06:54
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0006_review_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_of_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
