# Generated by Django 5.0.4 on 2024-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist", "0007_watchlist_avg_rating_watchlist_number_of_ratings"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="sum_of_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
